apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- namespace.yaml
- ./../../base

patches:
- path: configmap.yaml
- path: ingress.yaml

images:
- name: PROJECT/BROADCASTER
  newName: ghcr.io/rororo06/broadcaster
  newTag: e7f1acf5a1c9bfc34f099679a154e6ca8d23792c
- name: PROJECT/TODO_APP
  newName: ghcr.io/rororo06/todo-app
  newTag: e7f1acf5a1c9bfc34f099679a154e6ca8d23792c
- name: PROJECT/TODO_BACKEND
  newName: ghcr.io/rororo06/todo-backend
  newTag: e7f1acf5a1c9bfc34f099679a154e6ca8d23792c
