apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- namespace.yaml
- ./../../base

patches:
- path: configmap.yaml
- path: ingress.yaml

images:
- name: PROJECT/BROADCASTER
  newName: ghcr.io/rororo06/broadcaster
  newTag: b289b8b3cbfd0d5a4139c809146927e0629c65af
- name: PROJECT/TODO_APP
  newName: ghcr.io/rororo06/todo-app
  newTag: b289b8b3cbfd0d5a4139c809146927e0629c65af
- name: PROJECT/TODO_BACKEND
  newName: ghcr.io/rororo06/todo-backend
  newTag: b289b8b3cbfd0d5a4139c809146927e0629c65af
