apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- namespace.yaml
- ./../../base

patches:
- path: configmap.yaml
- path: ingress.yaml

images:
- name: PROJECT/BROADCASTER
  newName: ghcr.io/rororo06/broadcaster
  newTag: f5de0fdcb69c768e5644ccfefb9f30f205419999
- name: PROJECT/TODO_APP
  newName: ghcr.io/rororo06/todo-app
  newTag: f5de0fdcb69c768e5644ccfefb9f30f205419999
- name: PROJECT/TODO_BACKEND
  newName: ghcr.io/rororo06/todo-backend
  newTag: f5de0fdcb69c768e5644ccfefb9f30f205419999
