apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  annotations:
    iam.gke.io/gcp-service-account: my-storage-sa@speedy-atom-500823-f0.iam.gserviceaccount.com
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup-cronjob
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: backup-sa
          volumes:
            - name: dump
              emptyDir: {}
          initContainers:
            - name: pg-dump
              image: postgres:18.0
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
              env:
                - name: PGHOST
                  valueFrom:
                    configMapKeyRef:
                      name: project-configmap
                      key: POSTGRES_HOST
                - name: PGDATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: project-configmap
                      key: POSTGRES_DATABASE
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
              volumeMounts:
                - name: dump
                  mountPath: /backup
              command:
                - sh
                - -c
                - pg_dump > /backup/backup.sql
          containers:
            - name: database-backup
              image: google/cloud-sdk:511.0.0-slim
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              env:
                - name: BACKUP_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: project-configmap
                      key: BACKUP_BUCKET
              volumeMounts:
                - name: dump
                  mountPath: /backup
              command:
                - sh
                - -c
                - gcloud storage cp /backup/backup.sql "gs://$BACKUP_BUCKET/todo-$(date +%Y-%m-%dT%H-%M-%S).sql"
