apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-production

resources:
- namespace.yaml
- ./../../base
- backup-cronjob.yaml

patches:
- path: configmap.yaml
- path: ingress.yaml
- path: broadcaster.yaml

images:
- name: PROJECT/BROADCASTER
  newName: ghcr.io/rororo06/broadcaster
  newTag: "5.8"
- name: PROJECT/TODO_APP
  newName: ghcr.io/rororo06/todo-app
  newTag: "5.8"
- name: PROJECT/TODO_BACKEND
  newName: ghcr.io/rororo06/todo-backend
  newTag: "5.8"
