apiVersion: v1
kind: ConfigMap
metadata:
  name: project-configmap
data:
  PORT: "3000"
  TODO_BACKEND_URL: http://todo-backend-svc:2345
  IMAGE_URL: https://picsum.photos/1200
  IMAGE_DIR: /usr/src/app/files
  IMAGE_CACHE_MINUTES: "10"
  TODO_MAX_LENGTH: "140"
  POSTGRES_HOST: postgres-svc
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: todos
  NATS_URL: nats://my-nats.nats.svc.cluster.local:4222
  NATS_SUBJECT: todos
  NATS_QUEUE_GROUP: broadcasters
  BACKUP_BUCKET: dwk-todo-backups-speedy-atom-500823-f0
