apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
  - cronjob.yaml
  - todo-app/deployment.yaml
  - todo-app/service.yaml
  - todo-app/ingress.yaml
  - todo-backend/deployment.yaml
  - todo-backend/service.yaml
  - broadcaster/deployment.yaml
